// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "open-cluster-management.io/api/work/v1alpha1"
)

// FakeReferenceWorks implements ReferenceWorkInterface
type FakeReferenceWorks struct {
	Fake *FakeWorkV1alpha1
	ns   string
}

var referenceworksResource = schema.GroupVersionResource{Group: "work.open-cluster-management.io", Version: "v1alpha1", Resource: "referenceworks"}

var referenceworksKind = schema.GroupVersionKind{Group: "work.open-cluster-management.io", Version: "v1alpha1", Kind: "ReferenceWork"}

// Get takes name of the referenceWork, and returns the corresponding referenceWork object, and an error if there is any.
func (c *FakeReferenceWorks) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ReferenceWork, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(referenceworksResource, c.ns, name), &v1alpha1.ReferenceWork{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ReferenceWork), err
}

// List takes label and field selectors, and returns the list of ReferenceWorks that match those selectors.
func (c *FakeReferenceWorks) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ReferenceWorkList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(referenceworksResource, referenceworksKind, c.ns, opts), &v1alpha1.ReferenceWorkList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ReferenceWorkList{ListMeta: obj.(*v1alpha1.ReferenceWorkList).ListMeta}
	for _, item := range obj.(*v1alpha1.ReferenceWorkList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested referenceWorks.
func (c *FakeReferenceWorks) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(referenceworksResource, c.ns, opts))

}

// Create takes the representation of a referenceWork and creates it.  Returns the server's representation of the referenceWork, and an error, if there is any.
func (c *FakeReferenceWorks) Create(ctx context.Context, referenceWork *v1alpha1.ReferenceWork, opts v1.CreateOptions) (result *v1alpha1.ReferenceWork, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(referenceworksResource, c.ns, referenceWork), &v1alpha1.ReferenceWork{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ReferenceWork), err
}

// Update takes the representation of a referenceWork and updates it. Returns the server's representation of the referenceWork, and an error, if there is any.
func (c *FakeReferenceWorks) Update(ctx context.Context, referenceWork *v1alpha1.ReferenceWork, opts v1.UpdateOptions) (result *v1alpha1.ReferenceWork, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(referenceworksResource, c.ns, referenceWork), &v1alpha1.ReferenceWork{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ReferenceWork), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeReferenceWorks) UpdateStatus(ctx context.Context, referenceWork *v1alpha1.ReferenceWork, opts v1.UpdateOptions) (*v1alpha1.ReferenceWork, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(referenceworksResource, "status", c.ns, referenceWork), &v1alpha1.ReferenceWork{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ReferenceWork), err
}

// Delete takes name of the referenceWork and deletes it. Returns an error if one occurs.
func (c *FakeReferenceWorks) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(referenceworksResource, c.ns, name, opts), &v1alpha1.ReferenceWork{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeReferenceWorks) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(referenceworksResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ReferenceWorkList{})
	return err
}

// Patch applies the patch and returns the patched referenceWork.
func (c *FakeReferenceWorks) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ReferenceWork, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(referenceworksResource, c.ns, name, pt, data, subresources...), &v1alpha1.ReferenceWork{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ReferenceWork), err
}
